// ponytail: flat mapping, no reflection or auto-detection, add aliases as needed
const FIELD_MAP = {
  "记录ID": "source_record_id",
  "观察者": "observer",
  "观察者ID": "observer_id",
  "观察日期": "event_date",
  "识别日期": "date_identified",
  "中文名": "chinese_name",
  "学名": "scientific_name",
  "学名ID": "scientific_name_id",
  "科": "family",
  "科中文名": "family_chinese_name",
  "属": "genus",
  "属中文名": "genus_chinese_name",
  "国家": "country",
  "省": "province",
  "市": "city",
  "区县": "county",
  "经度": "longitude",
  "纬度": "latitude",
  "海拔": "elevation",
  "位置ID": "location_id",
  "来源类型": "establishment_means",
  "生境类型": "habitat_type",
  "访花昆虫": "associated_taxa",
  "备注": "remarks",
  "原始识别文本": "verbatim_identification",
  "识别人": "identified_by",
  "识别人ID": "identified_by_id",
  "审核状态": "verification_status",
  "图片链接": "media_url",
  "图片链接列表": "media_urls",
  "原始图片链接": "source_media_urls",
  "数据集名称": "dataset_name",
  "数据集ID": "dataset_id",
  "许可证": "license",

  "source_record_id": "source_record_id",
  "observer": "observer",
  "observer_id": "observer_id",
  "eventDate": "event_date",
  "event_date": "event_date",
  "dateIdentified": "date_identified",
  "date_identified": "date_identified",
  "chineseName": "chinese_name",
  "chinese_name": "chinese_name",
  "scientificName": "scientific_name",
  "scientific_name": "scientific_name",
  "scientificNameId": "scientific_name_id",
  "scientific_name_id": "scientific_name_id",
  "familyChineseName": "family_chinese_name",
  "family_chinese_name": "family_chinese_name",
  "genusChineseName": "genus_chinese_name",
  "genus_chinese_name": "genus_chinese_name",
  "establishmentMeans": "establishment_means",
  "establishment_means": "establishment_means",
  "habitatType": "habitat_type",
  "habitat_type": "habitat_type",
  "associatedTaxa": "associated_taxa",
  "associated_taxa": "associated_taxa",
  "verbatimIdentification": "verbatim_identification",
  "verbatim_identification": "verbatim_identification",
  "identifiedBy": "identified_by",
  "identified_by": "identified_by",
  "identifiedById": "identified_by_id",
  "identified_by_id": "identified_by_id",
  "verificationStatus": "verification_status",
  "verification_status": "verification_status",
  "mediaUrls": "media_urls",
  "media_urls": "media_urls",
  "sourceMediaUrls": "source_media_urls",
  "source_media_urls": "source_media_urls",
  "datasetName": "dataset_name",
  "dataset_name": "dataset_name",
  "datasetId": "dataset_id",
  "dataset_id": "dataset_id",
  "locationId": "location_id",
  "location_id": "location_id",
};

const REQUIRED_FIELDS = ["event_date", "chinese_name", "scientific_name", "city", "observer"];

export { FIELD_MAP, REQUIRED_FIELDS };
